# Generated by Django 5.2.14 on 2026-06-01 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA включена'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_2fa_remember_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Запомнить устройство до'),
        ),
        migrations.AddField(
            model_name='user',
            name='remember_device_token',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Токен устройства'),
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Код')),
                ('purpose', models.CharField(choices=[('login', 'Вход в систему'), ('password_reset', 'Сброс пароля')], max_length=20, verbose_name='Назначение')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('attempts_left', models.IntegerField(default=5, verbose_name='Осталось попыток')),
                ('used', models.BooleanField(default=False, verbose_name='Использован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Email OTP',
                'verbose_name_plural': 'Email OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose', 'created_at'], name='api_emailot_email_ac71b9_idx')],
            },
        ),
    ]
