# Generated by Django 5.2.14 on 2026-06-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_2fa_enabled_user_last_2fa_remember_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Email подтвержден'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('login', 'Вход в систему'), ('password_reset', 'Сброс пароля'), ('verify_email', 'Подтверждение email')], max_length=20, verbose_name='Назначение'),
        ),
    ]
