# Generated by Django 5.2.14 on 2026-06-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_is_email_verified_alter_emailotp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visible_only_for_creator',
            field=models.BooleanField(default=False, verbose_name='Видно только организатору'),
        ),
    ]
